---
# setup tasks for Debian 13

- name: install packages
  tags: [system]
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - logrotate
    - firewalld
